Repository hmcts/rd-judicial-data-load, pull requests merged in 2020-10, with the labels that each got.

#144 fix: Nightly fix jrd
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-144

#145 Removed unused resources and string interpolations
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
  infrastructure/test_config.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-145

#146 TF Upgrade to 13.3 and Azure RM to 2.25+ - Master
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-146

#148 build(deps):Bum up data-ingestion lib to fix health check
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-148

#149 Fix : Bump up versions and owasp update(RDCC-1933)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-149

#150 RDCC-1928 Moving integration test cases to functional
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchAuditingAndEmailTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBatchIntegrationSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBlobSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/LeafIntegrationTestSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/RestartingSpringJUnit4ClassRunner.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/SpringRestarter.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/LeafCamelConfig.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/application-leaf-integration.yml
  src/functionalTest/resources/db/testmigration/V1_1__init_tables.sql
  src/functionalTest/resources/db/testmigration/V1_2__alter_jrd_tables.sql
  src/functionalTest/resources/db/testmigration/V1_3__excption_table.sql
  src/functionalTest/resources/db/testmigration/V1_4__audit_table.sql
  src/functionalTest/resources/db/testmigration/V1_5__alter_user_profile.sql
  src/functionalTest/resources/db/testmigration/V1_6__drop_and_recreate_auth_table.sql
  src/functionalTest/resources/sourceFiles/leaf/BaseLocations.csv
  src/functionalTest/resources/sourceFiles/leaf/BaseLocations_jsr.csv
  src/functionalTest/resources/sourceFiles/leaf/Contracts-invalid-header.csv
  src/functionalTest/resources/sourceFiles/leaf/Contracts.csv
  src/functionalTest/resources/sourceFiles/leaf/Contracts_jsr.csv
  src/functionalTest/resources/sourceFiles/leaf/Locations.csv
  src/functionalTest/resources/sourceFiles/leaf/Locations_jsr.csv
  src/functionalTest/resources/sourceFiles/leaf/Roles.csv
  src/functionalTest/resources/sourceFiles/leaf/Roles_jsr.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_elinks_missing.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_error.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_invalid_jsr_parent_elinks.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_invalidheader.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_jsr.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_jsr_exccedthreshold.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_singlerecord.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation_elinks_missings.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation_invalidheader.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation_jsr_partial_success.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation_singlerecord.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_jsr.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_singlerecord.csv
  src/functionalTest/resources/testData/default-leaf-load.sql
  src/functionalTest/resources/testData/truncate-exception.sql
  src/functionalTest/resources/testData/truncate-leaf.sql
  src/functionalTest/resources/testData/truncate-parent.sql
  src/integrationTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/IntegrationTestSupport.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/listener/JobResultListenerTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/task/LeafRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/task/ParentRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecuterTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-150

#151 adding suppression entry to fix the build
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-151

#152 feat: Updated Audit/Exceptions and stale file check with data-ingestion (RDCC-1924)
  build.gradle
  charts/rd-judicial-data-load/Chart.yaml
  charts/rd-judicial-data-load/values.preview.template.yaml
  charts/rd-judicial-data-load/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchAuditingAndEmailTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdFileStatusCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBatchIntegrationSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBlobSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_7__alter_audit_exception_table.sql
  src/main/java/uk/gov/hmcts/reform/juddata/JudicialApplication.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/service/JudicialAuditServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/task/ParentRouteTask.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdConstants.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutor.java
  src/main/java/uk/gov/hmcts/reform/juddata/configuration/BatchConfig.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialAuditServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/task/ParentRouteTaskTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/DataLoadUtilTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecuterTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-152
