Repository hmcts/rd-judicial-data-load, pull requests merged in 2020-12, with the labels that each got.

#155 fix: Audit service fix for multiple spring tasklets
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/application-leaf-integration.yml
  src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialOfficeAppointmentRowMapper.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutor.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-jrd-leaf-router.yaml
  src/main/resources/application-jrd-router-orchestartion.yaml
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialBaseLocationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialContractTypeProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialRegionTypeProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserRoleTypeProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecuterTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-155

#157 build: Addressed CVEs CVE-2020-25649 CVE-2020-17527
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-157

#156 Add sync method call
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-156

#158 fix : RDCC-2125 set full name if known_as field value is missing
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialUserProfileRowMapper.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialUserProfileRowMapperTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-158

#159 Fix the cve-2020-8908
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-159
