Repository hmcts/rd-judicial-data-load, pull requests merged in 2021-12, with the labels that each got.

#312 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-312

#313 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-313

#315 fix: patch log4j to the 2.16.0 in all applications to fix CVE-2021-45046
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-315

#311 Bugfix: Duplicate sidam id publishing to ASB
  build.gradle
  src/functionalTest/resources/application-integration.yml
  src/integrationTest/resources/application-integration-test.yml
  src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java
  src/main/resources/application-camel-routes-common.yaml
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-311

#316 fix: RDCC-3782 Added dependabot.yml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-316

#329 Fix: Upgrading log4j to fix CVE-2021-45105
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-329
