Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-04, with the labels that each got.

#393 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-393

#397 Nightly Build failure issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-397

#401 RDCC-4504 JRD LOAD -Nightly build failure -25/04/2022
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-401

#398 RDCC-4353 java 17
  Dockerfile
  build.gradle
  docker-compose.yml
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-398

#402 Feature/rdcc 4458
  README.md
  src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessor.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessor.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-402
