Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-09, with the labels that each got.

#480 Rdcc 5392 adding suppression for CVE 2022 25857
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-480

#481 fix: RDCC-5447 Suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-481

#482 RDCC-5496: excluding `jettison` to fix `CVE-2022-40149` & `CVE-2022-40150`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-482
