Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-05, with the labels that each got.

#404 send email in html free marker template for jrd user profiles
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/simple-template-userProfile.ftl
  src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdUserProfileUtil.java
  src/main/resources/application.yaml
  src/main/resources/templates/simple-template-userProfile.ftl
  src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdUserProfileUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-404

#405 Rdcc 4580
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java
  src/functionalTest/resources/application-integration.yml
  src/main/resources/application-jrd-router-orchestartion.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-405

#413 fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty
  build.gradle
  src/test/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfileTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/helper/JrdTestSupport.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-413

#414 fixed the region_type
  src/main/resources/application-jrd-leaf-router.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-414

#415 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-415

#416 RDCC-4699: CVE fix for tomcat embed
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-416

#418 CVE fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-418
