Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-08, with the labels that each got.

#465 RDCC-5261: Upgrading postgresql to version 42.4.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-465

#464 Judicial - Update Ticket Code to Service Code mapping for Family Private Law & Adoption Service
  src/functionalTest/resources/db/testmigration/V1_38__update_judicial_service_code_mapping.sql
  src/main/resources/db/migration/V1_38__update_judicial_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-464

#472 RDCC-4053 removed the cve suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-472

#474 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-474

#473 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-473
