Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-12, with the labels that each got.

#499 ElinksFeignClient , api key changes
  build.gradle
  charts/rd-judicial-data-load/values.preview.template.yaml
  charts/rd-judicial-data-load/values.yaml
  src/main/java/uk/gov/hmcts/reform/elinks/configuration/ElinksFeignInterceptorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/elinks/configuration/FeignConfiguration.java
  src/main/java/uk/gov/hmcts/reform/elinks/configuration/FeignHeaderConfig.java
  src/main/java/uk/gov/hmcts/reform/elinks/feign/ElinksFeignClient.java
  src/main/java/uk/gov/hmcts/reform/elinks/util/RefDataConstants.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-499

#504 Replace after with afterSuccess for depreciated : RDCC-5931
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-504

#505 CVE-2021-37533 Issue Suppression : RDCC - 6007
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-505

#508 RDCC-5940 deleting duplicate config
  src/main/java/uk/gov/hmcts/reform/elinks/configuration/FeignConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-508

#519 Feat:RDCC-6027:eLinks : Update the tables for Judicial Reference Data
  src/functionalTest/resources/db/testmigration/V1_48__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_48__elinks_alter_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-519

#524 Feat:RDCC-6048:Altered tables for elinks people api
  src/functionalTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_50__elinks_alter_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-524

#512 eLinks : Write audit utility method for updating dataload_schedular_audit table : RDCC 6001
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/resources/db/testmigration/V1_49__elinks_alter_dataload_schedular_audit.sql
  src/main/java/uk/gov/hmcts/reform/elinks/domain/ElinkDataSchedularAudit.java
  src/main/java/uk/gov/hmcts/reform/elinks/repository/ElinkSchedularAuditRepository.java
  src/main/java/uk/gov/hmcts/reform/elinks/util/ElinkDataIngestionSchedularAudit.java
  src/main/resources/db/migration/V1_49__elinks_alter_dataload_schedular_audit.sql
  src/test/java/uk/gov/hmcts/reform/juddata/camel/elinks/domain/ElinkDataSchedularAuditTest.java
  src/test/java/uk/gov/hmcts/reform/juddata/camel/elinks/util/ElinkDataIngestionSchedularAuditTest.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-512

#527 RDCC-6061: Adding Suppression for `CVE-2022-41881`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-527

#528 RDCC-6073: Fix for `CVE-2022-41915`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-528
