Repository hmcts/rd-judicial-data-load, pull requests merged in 2022-10, with the labels that each got.

#483 RDCC-5534: Upgrading `launchdarkly-java-server-sdk` & `snakeyaml`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-483

#484 CVE issue-Jackson Version fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-484

#486 CVE Issue Fix RDCC- 5675
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-486

#485 RDCC-5616
  src/functionalTest/resources/db/testmigration/V1_39__insert_judicial_location_mapping.sql
  src/main/resources/db/migration/V1_39__insert_judicial_location_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-485
