Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-01, with the labels that each got.

#529 RDCC-6118: Adding suppression for `CVE-2021-4277`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-529

#530 RDCC-6130: Adding suppressions for `CVE-2022-3064` & `CVE-2021-4235`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-530

#537 Email change
  src/functionalTest/resources/application-integration.yml
  src/integrationTest/resources/application-integration-test.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-537
