Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-07, with the labels that each got.

#599 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-599

#600 eLinks : Populate the data in cft_region_type table using flyway script.
  build.gradle
  src/main/resources/db/migration/V1_63__elinks_insert_cft_region_type_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-600

#602 updating sidam qeury for the the first run.
  src/main/resources/application-camel-routes-common.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-602

#603 Update IDAM query
  src/main/resources/application-camel-routes-common.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-603

#604 Rdcc 6883 :: eLinks : Data model changes for eLinks V5.0
  charts/rd-judicial-data-load/Chart.yaml
  src/functionalTest/resources/db/testmigration/V1_65__elinks_sequence_judicial_role_type_table.sql
  src/functionalTest/resources/db/testmigration/V1_66__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_65__elinks_sequence_judicial_role_type_table.sql
  src/main/resources/db/migration/V1_66__elinks_alter_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-604

#607 Suppress CVE-2023-34442 - working on fix
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-607

#605 eLinks flyway changes
  config/owasp/suppressions.xml
  src/main/resources/db/migration/V1_67__elinks_alter_tables.sql
  src/main/resources/db/migration/V1_68__elinks_insert_judicial_location_mapping_tables.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-605
