Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-06, with the labels that each got.

#584 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-584

#589 removed suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-589

#591 DTSRD-555: fix CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-591

#569 Feat:JRD : Update the existing file based ETL ingestion
  README.md
  config/owasp/suppressions.xml
  src/functionalTest/resources/application-integration.yml
  src/functionalTest/resources/db/testmigration/V1_61__alter_judicial_user_profile_extracted_date.sql.sql
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_constraints_error.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_invalid_jsr_parent_per.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_invalidheader.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_jsr.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_per_missing.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_singlerecord.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_appointments_with_foreignkey_violations.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_jsr.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_multiple_rows.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_singlerecord.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_with_invalid_appointment.csv
  src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_with_invalid_percode_objectId.csv
  src/integrationTest/resources/application-integration-test.yml
  src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialOfficeAppointment.java
  src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java
  src/main/resources/application-camel-routes-common.yaml
  src/main/resources/application-jrd-leaf-router.yaml
  src/main/resources/application-jrd-router-orchestartion.yaml
  src/main/resources/db/migration/V1_61__alter_judicial_user_profile_extracted_date.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-569

#594 Renovate config
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-594

#590 Update README.md
  README.md
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-590
