Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-11, with the labels that each got.

#626 eLinks : Region Mapping Update
  src/functionalTest/resources/db/testmigration/V1_89__elinks_insert_jrd_lrd_region_mapping.sql
  src/main/resources/db/migration/V1_87__elinks_insert_jrd_lrd_region_mapping.sql
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-data-load-pr-626

#627 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-627

#628 Update suppressions.xml for CVE-2023-4759
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-628

#630 Addresses CVE-2023-36052, CVE-2023-35887
  build.gradle
  charts/rd-judicial-data-load/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-630

#631 changing fly way version to 88 and functional fly way
  src/functionalTest/resources/db/testmigration/V1_90__elinks_insert_location_mapping_jrd_lrd.sql
  src/main/resources/db/migration/V1_88__elinks_insert_location_mapping_jrd_lrd.sql
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-data-load-pr-631

#629 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-629

#632 Update Service Code Mapping table
  src/functionalTest/resources/db/testmigration/V1_91__elinks_insert_service_code_mapping.sql
  src/main/resources/db/migration/V1_89__elinks_insert_service_code_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-632

#633 alter judicial_user_profile
  src/functionalTest/resources/db/testmigration/V1_92__elinks_alter_judicIal_userProfile.sql
  src/main/resources/db/migration/V1_90__elinks_alter_judicial_user_profile.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-633
