Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-12, with the labels that each got.

#635 Addresses CVE-2023-34055, CVE-2023-46589
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-635

#637 eLinks : Region Mapping Update for eLinks Go-Live
  src/functionalTest/resources/db/testmigration/V1_93__elinks_alter_judicIal_userProfile.sql
  src/main/resources/db/migration/V1_91__elinks_jrd_lrd_region_mapping.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-637

#639 Update dependencycheck to use default version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-639

#638 elinks : location mapping table update
  src/functionalTest/resources/db/testmigration/V1_94__elinks_jrd_lrd_region_mapping.sql
  src/main/resources/db/migration/V1_92__elinks_jrd_lrd_region_mapping.sql
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-judicial-data-load-pr-638
