Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-05, with the labels that each got.

#580 eLinks : Data model changes to support eLinks V5.0 API specifications
  config/owasp/suppressions.xml
  src/functionalTest/resources/db/testmigration/V1_58__elinks_alter.sql
  src/main/resources/db/migration/V1_58__elinks_alter.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-580

#582 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-582

#583 Scheduling nightly job to run an hour later
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-583

#587 DTSRD-456: fix CVE-2023-28709
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-587

#588 Upgrade chart-job to v 1.0.0
  charts/rd-judicial-data-load/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-588

#585 [RDCC-6746]upgrade deprecated methods to java 17
  src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-585
