Repository hmcts/rd-judicial-data-load, pull requests merged in 2023-09, with the labels that each got.

#614 DTSRD-1189
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-614

#617 Increase the length of the column row id from 32 to 256
  src/functionalTest/resources/db/testmigration/V1_84__elinks_alter_dataload_exception_records.sql
  src/main/resources/db/migration/V1_82__elinks_alter_dataload_exception_records.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-617

#616 DTSRD-1221
  .github/renovate.json
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-616

#615 eLinks: Create new table to store eLinks API response
  src/functionalTest/resources/db/testmigration/V1_80__elinks_service_code_mapping.sql
  src/functionalTest/resources/db/testmigration/V1_81__elinks_dataload_exception_records.sql
  src/functionalTest/resources/db/testmigration/V1_82__elinks_insert_judicial_location_mapping_tables.sql
  src/functionalTest/resources/db/testmigration/V1_83__judicial_service_code_mapping.sql
  src/functionalTest/resources/db/testmigration/V1_84__elinks_alter_dataload_exception_records.sql
  src/functionalTest/resources/db/testmigration/V1_85__elinks_create_elinks_responses_table.sql
  src/main/resources/db/migration/V1_78__elinks_service_code_mapping.sql
  src/main/resources/db/migration/V1_79__judicial_service_code_mapping.sql
  src/main/resources/db/migration/V1_80__elinks_insert_judicial_location_mapping_tables.sql
  src/main/resources/db/migration/V1_81__elinks_dataload_exception_records.sql
  src/main/resources/db/migration/V1_82__elinks_alter_dataload_exception_records.sql
  src/main/resources/db/migration/V1_83__elinks_create_elinks_responses_table.sql
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-615

#619 Change schedule to run at 9:10AM
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-judicial-data-load-pr-619
